# Generated by Django 4.1.7 on 2023-03-13 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15)),
                ('marca', models.CharField(max_length=15)),
                ('ano', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=15)),
                ('data_compra', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField(max_length=15)),
                ('endereço', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('data_aluguel', models.DateField()),
                ('data_entrega', models.DateField()),
                ('diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluguel.cliente')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluguel.carro')),
            ],
        ),
    ]
